Update version numbers
maputnik/desktop pull request #6
Opened 2019-10-08 20:32 UTC by pathmapper

2019-10-10 11:07 UTC, lukaswelte approved these changes

2019-10-10 11:08 UTC, lukaswelte commented
@pathmapper travis does not look good. It would be great to fix that first

2019-10-10 11:11 UTC, lukaswelte requested changes
Let's fix the Travis Build. 
Seems like it could not fetch the v1.6.0 editor

2019-10-10 12:03 UTC, pathmapper commented
Maybe the folder structure was not right, closing and reopen here to trigger a new build (hope it works).

2019-10-10 12:06 UTC, lukaswelte commented
@pathmapper you can trigger rebuilds in travis (just clicking the build and then there is a rebuild button)

2019-10-10 12:10 UTC, pathmapper commented
@lukaswelte, you're right. I wasn't logged in.

2019-10-10 12:28 UTC, pathmapper commented
@lukaswelte green build now (was an issue about how the public.zip was zipped).

2019-10-10 12:29 UTC, lukaswelte approved these changes
Awesome thanks for checking 👍

2019-10-10 12:30 UTC, merged

2019-10-10 12:30 UTC, lukaswelte commented
@pathmapper do you know who can remove the AppVeyor integration plus make Travis build to run successful mandatory?

2019-10-10 12:34 UTC, pathmapper commented
@lukaswelte , I think @lukasmartinelli could do it.

@orangemug do you know someone else?

See also:
https://github.com/maputnik/editor/issues/493

2019-10-30 06:52 UTC, pathmapper commented
@lukaswelte AppVeyor is now disabled https://github.com/maputnik/editor/issues/493#issuecomment-546725057.